package com.sample

import com.sample.Person;
import com.sample.Greeting;

query "get greeting"()
    greeting : Greeting()
end

rule "greet"
ruleflow-group "greet"
    when
    then
    	System.out.println("Hello from greet rule :)");
end

rule "greet master"
ruleflow-group "greet"
    when
        person : Person( name == "Ravishankar")
    then
        String salutation = "Hello Master" + person.getName() + "! your command is my wish {^_^}";
        insert(new Greeting(salutation));
end
rule "greet strangers"
ruleflow-group "greet"
    when
        person : Person( name != "Ravishankar")
    then
        String salutation = "Hello "+person.getName()+" , you are not my master dude. So please get out of my way (*_*) ";
        insert(new Greeting(salutation));
end