package com.sample;

import java.sql.Date;



/**
 * This class was automatically generated by the data modeler tool.
 */


public class ServiceOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

  
   private java.lang.Long id;

   
   @org.kie.api.definition.type.Label(value = "MSISDN")
   private java.lang.Integer msisdn;

   @org.kie.api.definition.type.Label(value = "DP Id")
   private java.lang.Integer dpId;

   @org.kie.api.definition.type.Label(value = "SCAP ID")
   private java.lang.Integer scapId;

   @org.kie.api.definition.type.Label(value = "Business Unit")
   private java.lang.String businessUnit;

   @org.kie.api.definition.type.Label(value = "Industry Code")
   private java.lang.String industryCode;

   @org.kie.api.definition.type.Label(value = "Country of Registration")
   private java.lang.String countryOfRegistration;

   @org.kie.api.definition.type.Label(value = "Profit Center")
   private java.lang.String profitCenter;
   
   private String requestId;
   private String  productCode;
   private String executedRule;
   private boolean isManualValidationRequired;
   private boolean isManualSegmentationRequired;
   private String salesRegion;
   private String salesRegionCode;
   private String dpName;
   private String billingProfileCode;
   private String arAccountCode;
   private String hardwareId;
   private String prevBusinessUnit;
   private String prevCommericialMarket;
   private String prevRuleId;
   private String imoNumber;
   private String grpPkgInstance;
   private String wholeSaleCust;
   private String corporateName;
   private String subscriber;
   private String verticalMarket;
   private String castOrgName;
   private String castVerticalMarket;
   private String vesselName;
   private String vesselType;
   private String aircraftClass;
   private String aircraftModel;
   private String aircraftManufacturer;
   private String tailNumber;
   private String callSign;
   private String createdBy;
   private String updatedBy;
   private Date createdTime;
   private Date updatedTime;
   private String errorMessage;

   public ServiceOrder()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getMsisdn()
   {
      return this.msisdn;
   }

   public void setMsisdn(java.lang.Integer msisdn)
   {
      this.msisdn = msisdn;
   }

   public java.lang.Integer getDpId()
   {
      return this.dpId;
   }

   public void setDpId(java.lang.Integer dpId)
   {
      this.dpId = dpId;
   }

   public java.lang.Integer getScapId()
   {
      return this.scapId;
   }

   public void setScapId(java.lang.Integer scapId)
   {
      this.scapId = scapId;
   }

   public java.lang.String getBusinessUnit()
   {
      return this.businessUnit;
   }

   public void setBusinessUnit(java.lang.String businessUnit)
   {
      this.businessUnit = businessUnit;
   }

   public java.lang.String getIndustryCode()
   {
      return this.industryCode;
   }

   public void setIndustryCode(java.lang.String industryCode)
   {
      this.industryCode = industryCode;
   }

   public java.lang.String getCountryOfRegistration()
   {
      return this.countryOfRegistration;
   }

   public void setCountryOfRegistration(java.lang.String countryOfRegistration)
   {
      this.countryOfRegistration = countryOfRegistration;
   }

   public java.lang.String getProfitCenter()
   {
      return this.profitCenter;
   }

   public void setProfitCenter(java.lang.String profitCenter)
   {
      this.profitCenter = profitCenter;
   }

   public ServiceOrder(java.lang.Long id, java.lang.Integer msisdn,
         java.lang.Integer dpId, java.lang.Integer scapId,
         java.lang.String businessUnit, java.lang.String industryCode,
         java.lang.String countryOfRegistration,
         java.lang.String profitCenter)
   {
      this.id = id;
      this.msisdn = msisdn;
      this.dpId = dpId;
      this.scapId = scapId;
      this.businessUnit = businessUnit;
      this.industryCode = industryCode;
      this.countryOfRegistration = countryOfRegistration;
      this.profitCenter = profitCenter;
   }

public String getRequestId() {
	return requestId;
}

public void setRequestId(String requestId) {
	this.requestId = requestId;
}

public String getProductCode() {
	return productCode;
}

public void setProductCode(String productCode) {
	this.productCode = productCode;
}

public String getExecutedRule() {
	return executedRule;
}

public void setExecutedRule(String executedRule) {
	this.executedRule = executedRule;
}

public boolean isManualValidationRequired() {
	return isManualValidationRequired;
}

public void setManualValidationRequired(boolean isManualValidationRequired) {
	this.isManualValidationRequired = isManualValidationRequired;
}

public boolean isManualSegmentationRequired() {
	return isManualSegmentationRequired;
}

public void setManualSegmentationRequired(boolean isManualSegmentationRequired) {
	this.isManualSegmentationRequired = isManualSegmentationRequired;
}

public String getSalesRegion() {
	return salesRegion;
}

public void setSalesRegion(String salesRegion) {
	this.salesRegion = salesRegion;
}

public String getSalesRegionCode() {
	return salesRegionCode;
}

public void setSalesRegionCode(String salesRegionCode) {
	this.salesRegionCode = salesRegionCode;
}

public String getDpName() {
	return dpName;
}

public void setDpName(String dpName) {
	this.dpName = dpName;
}

public String getBillingProfileCode() {
	return billingProfileCode;
}

public void setBillingProfileCode(String billingProfileCode) {
	this.billingProfileCode = billingProfileCode;
}

public String getArAccountCode() {
	return arAccountCode;
}

public void setArAccountCode(String arAccountCode) {
	this.arAccountCode = arAccountCode;
}

public String getHardwareId() {
	return hardwareId;
}

public void setHardwareId(String hardwareId) {
	this.hardwareId = hardwareId;
}

public String getPrevBusinessUnit() {
	return prevBusinessUnit;
}

public void setPrevBusinessUnit(String prevBusinessUnit) {
	this.prevBusinessUnit = prevBusinessUnit;
}

public String getPrevCommericialMarket() {
	return prevCommericialMarket;
}

public void setPrevCommericialMarket(String prevCommericialMarket) {
	this.prevCommericialMarket = prevCommericialMarket;
}

public String getPrevRuleId() {
	return prevRuleId;
}

public void setPrevRuleId(String prevRuleId) {
	this.prevRuleId = prevRuleId;
}

public String getImoNumber() {
	return imoNumber;
}

public void setImoNumber(String imoNumber) {
	this.imoNumber = imoNumber;
}

public String getGrpPkgInstance() {
	return grpPkgInstance;
}

public void setGrpPkgInstance(String grpPkgInstance) {
	this.grpPkgInstance = grpPkgInstance;
}

public String getWholeSaleCust() {
	return wholeSaleCust;
}

public void setWholeSaleCust(String wholeSaleCust) {
	this.wholeSaleCust = wholeSaleCust;
}

public String getCorporateName() {
	return corporateName;
}

public void setCorporateName(String corporateName) {
	this.corporateName = corporateName;
}

public String getSubscriber() {
	return subscriber;
}

public void setSubscriber(String subscriber) {
	this.subscriber = subscriber;
}

public String getVerticalMarket() {
	return verticalMarket;
}

public void setVerticalMarket(String verticalMarket) {
	this.verticalMarket = verticalMarket;
}

public String getCastOrgName() {
	return castOrgName;
}

public void setCastOrgName(String castOrgName) {
	this.castOrgName = castOrgName;
}

public String getCastVerticalMarket() {
	return castVerticalMarket;
}

public void setCastVerticalMarket(String castVerticalMarket) {
	this.castVerticalMarket = castVerticalMarket;
}

public String getVesselName() {
	return vesselName;
}

public void setVesselName(String vesselName) {
	this.vesselName = vesselName;
}

public String getVesselType() {
	return vesselType;
}

public void setVesselType(String vesselType) {
	this.vesselType = vesselType;
}

public String getAircraftClass() {
	return aircraftClass;
}

public void setAircraftClass(String aircraftClass) {
	this.aircraftClass = aircraftClass;
}

public String getAircraftModel() {
	return aircraftModel;
}

public void setAircraftModel(String aircraftModel) {
	this.aircraftModel = aircraftModel;
}

public String getAircraftManufacturer() {
	return aircraftManufacturer;
}

public void setAircraftManufacturer(String aircraftManufacturer) {
	this.aircraftManufacturer = aircraftManufacturer;
}

public String getTailNumber() {
	return tailNumber;
}

public void setTailNumber(String tailNumber) {
	this.tailNumber = tailNumber;
}

public String getCallSign() {
	return callSign;
}

public void setCallSign(String callSign) {
	this.callSign = callSign;
}

public String getCreatedBy() {
	return createdBy;
}

public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
}

public String getUpdatedBy() {
	return updatedBy;
}

public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
}

public Date getCreatedTime() {
	return createdTime;
}

public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
}

public Date getUpdatedTime() {
	return updatedTime;
}

public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
}

public static long getSerialversionuid() {
	return serialVersionUID;
}


public String getErrorMessage() {
	return errorMessage;
}

public void setErrorMessage(String errorMessage) {
	this.errorMessage = errorMessage;
}

@Override
public String toString() {
	return "ServiceOrder [id=" + id + ", msisdn=" + msisdn + ", dpId=" + dpId + ", scapId=" + scapId + ", businessUnit="
			+ businessUnit + ", industryCode=" + industryCode + ", countryOfRegistration=" + countryOfRegistration
			+ ", profitCenter=" + profitCenter + ", requestId=" + requestId + ", productCode=" + productCode
			+ ", executedRule=" + executedRule + ", isManualValidationRequired=" + isManualValidationRequired
			+ ", isManualSegmentationRequired=" + isManualSegmentationRequired + ", salesRegion=" + salesRegion
			+ ", salesRegionCode=" + salesRegionCode + ", dpName=" + dpName + ", billingProfileCode="
			+ billingProfileCode + ", arAccountCode=" + arAccountCode + ", hardwareId=" + hardwareId
			+ ", prevBusinessUnit=" + prevBusinessUnit + ", prevCommericialMarket=" + prevCommericialMarket
			+ ", prevRuleId=" + prevRuleId + ", imoNumber=" + imoNumber + ", grpPkgInstance=" + grpPkgInstance
			+ ", wholeSaleCust=" + wholeSaleCust + ", corporateName=" + corporateName + ", subscriber=" + subscriber
			+ ", verticalMarket=" + verticalMarket + ", castOrgName=" + castOrgName + ", castVerticalMarket="
			+ castVerticalMarket + ", vesselName=" + vesselName + ", vesselType=" + vesselType + ", aircraftClass="
			+ aircraftClass + ", aircraftModel=" + aircraftModel + ", aircraftManufacturer=" + aircraftManufacturer
			+ ", tailNumber=" + tailNumber + ", callSign=" + callSign + ", createdBy=" + createdBy + ", updatedBy="
			+ updatedBy + ", createdTime=" + createdTime + ", updatedTime=" + updatedTime + "]";
}


   
   

}